### ISSUE TITLE
Access i18n from model validations

### ISSUE THREAD

**Issue by Rafkraft** [lykmapipo/sails-hook-validation#12]
Hi

Thanks very much for this add-on , it was very much needed.

Could you telle me how to access i18n variables from the model validations ?

Thank you

**Comment by lykmapipo** [comment]
@Rafkraft 

Currently sails-hook-validation does not hook to sails i18n.
It assume developer can handle it.

But am on the way to implement the hook to sails i18n.

Am accepting suggestions.

**Comment by Rafkraft** [comment]
ok thanks :)

**Comment by lykmapipo** [comment]
@Rafkraft 

i18n support on the way. Next release will have it.
Thanks for the push.

**Comment by lykmapipo** [comment]
@Rafkraft 

v0.3.0 with support to i18n have been published to npm

**Comment by Rafkraft** [comment]
nice ! thanks very much !
