### ISSUE TITLE
fallback locale if specific locale is not provided

### ISSUE THREAD

**Issue by naxmefy** [lykmapipo/sails-hook-validation#13]
your example were:

``` JSON
{
    "authentication.email.required": "Email is required",
    "authentication.email.email": "Provide valid email address",
    "authentication.email.unique": "Email address is already taken",
    "authentication.username.required": "Username is required",
    "authentication.username.string": "Username is must be a valid string",
    "authentication.birthday.required": "Birthday is required",
    "authentication.birthday.date": "Birthday is not a valid date"
}
```

but it would be more great if default error messages would be available. E.g.:

``` JSON
{
  "default.required": "#{fieldName} is required",
  "default.unique": "#{fieldName} is already taken"
}
```

At least it would be perfect if the hook would provide a default setup of error messages, and anyone could easily overwrite the default setup with his locales.

**Comment by lykmapipo** [comment]
@Naxmeify 
By default `sails-hook-validation` uses your `sails default locale` to obtain error messages if the incoming request does not contain it. 

On other hand, an idea of fallback default message is good and i buy it. Any suggestion on how to go with it?

**Comment by Naxmeify** [comment]
i like the grails way to handle message codes and overwrite possibilities.

e.g.:
```
default.invalid.email.message=Property [{0}] of class [{1}] with value [{2}] is not a valid e-mail address

# Overwrite for on specific property in specific class
ClassName.PropertyName.invalid.email.message=My specific message if email validation failed
```

we could handle this inside the locales
```JSON
{
  "default.validation.message.for.email": "The default message"
}
```

For specific model (additional as overwrite of default):
```JSON
{
  "ModelName.validation.message.for.email":"My specific message"
}
```

the base fallback could be the orm error - but the possibility to generate default messages would be nice ^^

**Comment by lykmapipo** [comment]
@Naxmeify 

I like the way it is, but this hook was develop to give ability to add `custom validation error messages`.

I think sails already give you `default validation error messages` and you can access them on `error object`. Since `sails-hook-validation` does not override these errors, I think they can be used as default errors instead of us re-inventing the wheel.

The only thing that remains, is how can we offer these default error messages in different locale. That is where the issue exist.

Correct me if not.

**Comment by Naxmeify** [comment]
yes and no....

the possibility to define defaults is to specify default messages to overwrite in one step the english defaults of the orm....

if you overwrite it with the hook with one entry (per locale) u dont have to write the same message for every model

what u did?

1. you give an easy way to overwrite the defaults with the "HOOK-DEFAULTS"
2. i18n still exists

what is the bonus?

1. you can overwrite defaults with specific changes per model

e.g.:

You got 3 Models:

* User (with email attribute)
* Organization (with email attribute)
* Ticket (with supportAddress attribute -> has email validation)

the locale could be:

```JSON
{
  "default.validation.message.for.email": "#{AttributeName} in #{ModelName} is no valid email address",
  "Ticket.supportAddress.validation.message.for.email":"The Support Address for this Ticket is invalid"
}
```

you wrote default messages for attributes with email validation, but also defined a specific message for ticket model attribute supportAddress. the hook will look for specific messages but has a 2 fallbacks. 

1. The defined ``` default.validation.message.for.email ``` (will be used by User and Organization)
2. The orm defaults (will be used if no hook default or specific overwrite exists)

What is the win? i18n support is still given!!

E.g.: 
* for english
```JSON
{
  "default.validation.message.for.email": "#{AttributeName} in #{ModelName} is no valid email address",
  "Ticket.supportAddress.validation.message.for.email":"The Support Address for this Ticket is invalid"
}
```
* for german
```JSON
{
  "default.validation.message.for.email": "#{AttributeName} in #{ModelName} ist keine E-Mail Adresse",
  "Ticket.supportAddress.validation.message.for.email":"Die Support Adresse für dieses Ticket is ungültig"
}
```

**Comment by lykmapipo** [comment]
@Naxmeify 

I got you. You may send PR if you have an implementation, while am looking foward to implement this feature

Thanks
