### ISSUE TITLE
Errors in error.invalidAttributes but error.Errors is undefined

### ISSUE THREAD

**Issue by tkiethanom** [lykmapipo/sails-hook-validation#16]
My model looks liks this 

```javascript
module.exports = {
	types: {
		password: function(password){
			if(password != null){
				return password === this.confirm_password;
			}
			else{
				return true;
			}
		}
	},
	attributes: {
		id: {
			type: 'int',
			autoIncrement: true,
			primaryKey: true
		},
		email: {
			type: 'email',
		},
		password: {
			type: 'string',
			required: true,
			password: true
		},
		active: {
			type: 'boolean'
		},
		last_login_date: {
			type: 'datetime'
		}
	},
	validationMessages : {
		password: {
			password: 'Passwords do not match',
		},
		email: {
			email: 'testing',
		}
	},
};
```

In my controller I'm doing this 

```javascript
Admin.update({id: req.body.id}, saveData, function(err, result){							
	console.log(err.invalidAttributes);
	console.log(err.Errors);								
});
```

In my console the err.invalidAttributes has 
    
{ password:
   [ { rule: 'password',
       message: '"password" validation rule failed for input: \'fasdf\'' } ] }
    

while the err.Errors is undefined.

Am I missing something?
I ran npm install --save sails-hook-validation

My sails version is 0.11

**Comment by tkiethanom** [comment]
I've read that you need to have a matching validtionMessage for each attribute so I've simplified my model to 
```javascript
module.exports = {

	attributes: {
		test: {
			number: true
		}
	},
	validationMessages : {
		test: {
			number: 'test message',
		}
	},

};
```
Still the same results, the err.Errors is undefined but the err.invalidAttributes is populated.

**Comment by lykmapipo** [comment]
@tkiethanom 

May you please check this [spec](https://github.com/lykmapipo/testvalidation/blob/master/test/note.spec.js#L63) and [then this one](https://github.com/lykmapipo/testvalidation/blob/master/test/note.spec.js#L90). In the first case wihich cover your scenario `error.Errors` exist and in the second scenario if you update a model with empty hash sails will not update your data and thus no validation will be run.

You can check [this model](https://github.com/lykmapipo/testvalidation/blob/master/api/models/Note.js) for clean way to define your custom messages.

Hope it helps.
