### ISSUE TITLE
Can enums be validated?

### ISSUE THREAD

**Issue by anupsarode** [lykmapipo/sails-hook-validation#17]
I have a field named status in my User model. Any way I can have validation for that field?

```
status: 
        {
            type:         "string",
            enum:         ['activating', 'activated'],
            defaultsTo:   'activating',
            required:     true
        },
```

**Comment by lykmapipo** [comment]
@anupsarode

Sure you can, as long as you are using [valid sails validations rules](http://sailsjs.org/documentation/concepts/models-and-orm/validations) that applies to enums
