### ISSUE TITLE
Model.validation don´t return Errors 

### ISSUE THREAD

**Issue by vagnernascimento** [lykmapipo/sails-hook-validation#21]
Hi, I am implementing a app using i18n and Sails-hook-validation, everything works fine except when I try with MyModel.validation function. The functions create and update return the translated validation messages in Errors hash.
I had tested as static method and instance method and both has the same problem. Could you help me ?

**Comment by lykmapipo** [comment]
@vagnernascimento 

May you please share samples  codes that cause the problem.
I will appreciate that.

**Comment by lykmapipo** [comment]
@vagnernascimento 

checkout v0.4.3
