### ISSUE TITLE
NPM not updated ?

### ISSUE THREAD

**Issue by rishabhmhjn** [lykmapipo/sails-hook-validation#29]
Waiting for the commit(https://github.com/lykmapipo/sails-hook-validation/commit/493b19eb33b81df557dd801f9124ea6c25aa91e6) fix to be pushed to NPM

**Comment by lykmapipo** [comment]
@rishabhmhjn 

Am on it..

:+1:

**Comment by rishabhmhjn** [comment]
Thank you so much!

Waiting for it

**Comment by lykmapipo** [comment]
@rishabhmhjn 

published on v0.4.3
