### ISSUE TITLE
TypeError: request.getLocale is not a function

### ISSUE THREAD

**Issue by vromanchakvakoms** [lykmapipo/sails-hook-validation#33]
Hi there
When send request, got locale error,
how to turn off force locale checking?

file index.js

```
routes: {
            before: {
                'all /*': function grabLocale(request, response, next) {
                    //configure i18n current request locale
                    sails.config.i18n.requestLocale = request.getLocale(); //<-- error here

                    //continue
                    next();
                }
            }
        }
```

**Comment by 1vasari** [comment]
I'm getting this error because I have i18n disabled in my RESTful Sails API. Is there a solution to this?

**Comment by KSDaemon** [comment]
+1 for this. Sails-hook-validation doesn't work if i18n hook is turned off. 
Will be great to check i18n status and if it is off, then just return error messages from model description.

**Comment by sercanov** [comment]
+1
