### ISSUE TITLE
Errors on Sails 1.0 installations

### ISSUE THREAD

**Issue by macfeaster** [lykmapipo/sails-hook-validation#50]
Thanks for a great plugin!

With Sails 1.0, the plugin fails. These are the errors I have encountered so far:

- sails.util._ is no longer available (lodash is no longer included in sails), even when specifying a lodash instance in the configuration file.
- `sails.__ is not a function` - I do not know why this doesn't work, since it's still in the documentation

The first should be easily fixed by changing from the Sails built-in lodash to your own instance. Not sure about the second one though.

**Comment by hebertbanes** [comment]
you can fixed it changing the following at index.js:
`module.exports = function(sails) {
    //patch sails model
    //to add custom errors message
    //logic
    function patch() {
        sails
            .util
              ._
            .forEach(sails.models, function(model) {
                //bind path validate
                //on concrete models
                //and left derived model
                //build from associations
                if (model.globalId) {`

TO

`module.exports = function(sails) {
    //patch sails model
    //to add custom errors message
    //logic
    function patch() {
        //Hebert Update: sails.util._ doesnt exist anymore at v1.x
          Object.keys(sails.models).forEach(function (model){
                //bind path validate
                //on concrete models
                //and left derived model
                //build from associations
                if (model.globalId) {`
